name: Build and Upload ISO

on:
  pull_request:
    paths:
      - ".github/workflows/build-disk.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to pull images from GHCR if they are private

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ISO
        id: build-iso # Assign an ID to reference outputs
        uses: ublue-os/titanoboa@main
        with:
          # Replace with your actual container image reference
          image-ref: ghcr.io/shaunassam/tuqueos:latest
          flatpaks-list: ${{ github.workspace }}/flatpaks/system-flatpaks.list
          kargs: ""
          builder-distro: fedora

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: tuqueos # Name of the artifact in the GitHub UI
          # Titanoboa outputs the build directory path, which we use here
          path: ${{ steps.build-iso.outputs.output-directory }} 
          if-no-files-found: error # Fail the job if the ISO is not found
          retention-days: 7 # Optional: Set the retention period (default 90 days)
